name: Deploy on Push

on:
  push:
    branches:
      - master
  pull_request:
    types:
      - closed
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create .env file
        run: |
          echo "hello world"
          echo "${{ secrets.ENV }}" > .env 

      - name: Build and run containers
        run: |
          docker-compose down
          docker-compose --env-file .env up --build -d